config/routes.rb
Rails.application.routes.draw do
  get 'skills/index'

  root 'professions#index'
  get 'professions/status'
  get 'professions/get_skills_json'
  get 'professions/get_professions_json'

  resources :professions
  resources :skills

end

app/models/st_profession.rb
class StProfession < ActiveRecord::Base
  validates :name , presence: true,length: {minimum: 2}

end

app/models/st_skill.rb
class StSkill < ActiveRecord::Base
  PATH = "/Users/zjt/RubymineProjects/skill_tree_server/public/json/"
  def self.get_skill(id)
    skill = StSkill.find_by_id(id)
    stats_arr = skill.stats.split("|")
    stats_hash = {
        "title" => stats_arr[0],
        "value" => stats_arr[1]
    }
    stats_arr2 = [].push stats_hash
    #stats_json = Oj.dump
    arr = {"id" => skill.id,
      "title" => skill.title,
      "dependsOn" => get_dependson_arr(id),
      "description" => skill.description,
      "rankDescriptions" => skill.rankDescriptions.nil? ? nil : skill.rankDescriptions.split("|"),
      "links" => get_links_arr(id),
      "maxPoints" => skill.maxPoints,
      "stats" => stats_arr2
    }
    return arr
  end

  #得到转化为正确格式的stats
  def self.get_right_stats (id)
    skill = StSkill.find_by_id(id)
    stats_arr = skill.stats.split("|")
    stats_hash = {
        "title" => stats_arr[0],
        "value" => stats_arr[1].to_i
    }
    stats_arr2 = [].push stats_hash
    return stats_arr2
  end

  #得到转化为数字数组的dependsON
  def self.get_links_arr(id)
    arr = []
    skill = StSkill.find_by_id(id)
    return arr if skill.links.nil?
    origin_arr = skill.links.split("|")
    origin_hash = {
        "label" => origin_arr[0],
        "url" => origin_arr[1]
    }
    return [].push origin_hash
  end

  #得到转化为数字数组的dependsON
  def self.get_dependson_arr (id)
    arr = []
    skill = StSkill.find_by_id(id)
    return arr if skill.dependsOn.nil?
    origin_arr = skill.dependsOn.split("|")
    origin_arr.each do |item|
      arr.push item.to_i
    end
    return arr
  end


  def self.write_json
    StSkill.all.each do |skill|
      arr = {"id" => skill.id,
             "title" => skill.title,
             "dependsOn" => skill.dependsOn,
             "description" => skill.description,
             "rankDescriptions" => skill.rankDescriptions,
             "links" => skill.links,
             "maxPoints" => skill.maxPoints,
             "stats" => skill.stats
      }
      file = File.new(PATH+skill.title+".json","w")
      file.puts(JSON arr)
      file.close
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  Json_path = "/Users/zjt/RubymineProjects/skill_tree_server/public/json/"
end

app/controllers/professions_controller.rb
class ProfessionsController < ApplicationController
  #require 'rufus-scheduler'
  def new
    @profession = StProfession.new
  end

  def index
    @professions = StProfession.all
    #render :text => "This is profession"
    #render :json => {:hehe => "haha"}
  end

  def show
    @profession = StProfession.find(params[:id])
    array = @profession.skills.split(",")
    temp_directory = Json_path+@profession.name+"/"
    if File::directory?(temp_directory)
      Dir.foreach(temp_directory) do |item|
        if item!='.' and item!='..'
          File.delete(temp_directory+"/"+item)
        end
      end
    else
      Dir.mkdir(Json_path+@profession.name+"/")
    end
    file = File.new(Json_path+@profession.name+"/"+@profession.name+".json","w")
    file.puts("{\"skills\": [")
    for i in 0..array.length-2
      content = StSkill.get_skill array[i]
      file.puts(JSON content)
      file.puts(",")
    end
    file.puts(JSON StSkill.get_skill array[array.length-1])
    file.puts("]}")
    file.close
    @skills_num = array.length

  end

  def create
    @profession = StProfession.new()
  end

  def status

    #render :text => "what's this"
  end

  def get_skills_json
    @profession =StProfession.find(params[:id])  #StProfession.find(params[:id])
    array = @profession.skills.split("|")
    array_skills = []
    array.each do |item|
      content = StSkill.get_skill item
      array_skills.push content
    end
    hash_skills = {"skills" => array_skills}
    render :json => Oj.dump(hash_skills)
  end

  def get_professions_json
    array = []
    StProfession.all.each do |item|
      temp_hash = {"id" => item.id,
              "name" => item.name,
              "description" => item.description
      }
      array.push(temp_hash)
    end
    professions_hash = {"professions" => array}
    render :json => Oj.dump(professions_hash)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    #StSkill.write_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/professions_helper.rb
module ProfessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>技能树</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/professions/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>skilltree</title>
  <meta name="description" content="skilltree for test">
  <meta name="author" content="Zephyrus@http://lightrains.org">
  <link href="./css/layout.css" rel="stylesheet">
  <SCRIPT src="./js/jquery-latest.js" type=text/javascript></SCRIPT>

</head>
<body>
<div class="ltIE9-hide">
  <div class="ltIE9-hide">
    <div data-bind="css: { open: isOpen }" class="page">
      <div class="intro">
        <div class="left"></div>
        <div class="right"></div>
        <p>选择职业</p>
        <button data-bind="click: toggle" class="demo1" >产品经理</button>
        <button data-bind="click: toggle" class="demo2" >UI</button>
        <button data-bind="click: toggle" class="demo3" >程序员</button>
      </div>


      <div class="talent-tree">

        <!--	<h2 class="start-helper" data-bind="css:{active:noPointsSpent}">Start here!</h2>-->
        <!--ko foreach: skills-->
        <div data-bind="css: { 'can-add-points': canAddPoints, 'has-points': hasPoints, 'has-max-points': hasMaxPoints }, attr: { 'data-skill-id': id }" class="skill">
          <div data-bind="css: { active: dependenciesFulfilled }" class="skill-dependency"></div>
        </div>
        <!--/ko-->
        <!--ko foreach: skills-->
        <div data-bind="css: { 'can-add-points': canAddPoints, 'has-points': hasPoints, 'has-max-points': hasMaxPoints }, attr: { 'data-skill-id': id }" class="skill">
          <div class="icon-container">
            <div class="icon"></div>
          </div>
          <div class="frame">
            <div class="tool-tip">
              <h3 data-bind="text: title" class="skill-name"></h3>
              <div data-bind="html: description" class="skill-description"></div>
              <ul class="skill-links">
                <!--ko foreach: links-->
                <li>
                  <a data-bind="attr: { href: url }, click: function(){
										_gaq.push(['_trackEvent',$parent.title, label, url]);
										return true;
										}, text: label" target="_blank"></a>
                </li>
                <!--/ko-->
              </ul>
              <hr data-bind="visible: currentRankDescription() || nextRankDescription()">
              <div data-bind="if: currentRankDescription" class="current-rank-description">Current rank: <span data-bind="	text: currentRankDescription"></span></div>
              <div data-bind="if: nextRankDescription" class="next-rank-description">Next rank: <span data-bind="	text: nextRankDescription"></span></div>
              <hr>
              <ul class="stats">
                <!--ko foreach: stats-->
                <li><span class="value">+<span data-bind="text: value"></span></span> <span data-bind="	text: title" class="title"></span></li>
                <!--/ko-->
              </ul>
              <!--ko if: talentSummary-->
              <div class="talent-summary">Grants <span data-bind="text: talentSummary"></span></div>
              <!--/ko-->
              <div data-bind="text: helpMessage" class="help-message"></div>
            </div>
            <div class="skill-points"><span data-bind="text: points" class="points"></span>/<span data-bind="	text: maxPoints" class="max-points"></span></div>
            <div data-bind="click: addPoint, rightClick: removePoint" class="hit-area"></div>
          </div>
        </div>
        <!--/ko-->
      </div>
      <div class="avatar">
        <div class="portrait">
          <img data-bind="attr: { src: portraitURL }"></div>
        <div class="portrait-controls">
          <button data-bind="click: choosePreviousPortrait" class="left-button">&laquo;</button>&nbsp;<button data-bind="click: chooseNextPortrait" class="right-button">&raquo;</button>
        </div>
        <div class="details">
          <input data-bind="value: avatarName" class="h2"><div class="level">Level <span data-bind="	text: level" class="value"></span> Web Developer</div>
          <div data-bind="text: talentSummary" class="talent-summary"></div>
          <ul class="stats">
            <!--ko foreach: stats-->
            <li><span data-bind="text: title" class="title"></span>: <span data-bind="	text: value" class="value"></span></li>
            <!--/ko-->
          </ul>
        </div>
      </div>

    </div>
  </div>
  <div class="ltIE9-show ltIE9-warning">
    <h2>Please upgrade your browser!</h2>
    <p>Try one of these free options:</p>
    <ul>
      <li><a onclick="_gaq.push(['_trackEvent','external link','upgrade browser','Chrome']);" href="http://google.com/chrome" target="_blank">Google Chrome</a></li>
      <li><a onclick="_gaq.push(['_trackEvent','external link','upgrade browser','MSIE']);" href="http://windows.microsoft.com/en-US/internet-explorer/download-ie" target="_blank">Microsoft Internet Explorer 10</a></li>
      <li><a onclick="_gaq.push(['_trackEvent','external link','upgrade browser','Firefox']);" href="www.mozilla.org/en-US/firefox" target="_blank">Mozilla Firefox</a></li>
    </ul>
  </div>


  <script src="./js/jquery.min.js"></script>
  <script src="./js/knockout.min.js"></script>
  <script src="./js/skilltree.min.js"></script>
  <script src="./js/default.js"></script>
</body>
</html>

app/views/professions/show.html.erb
<h1><%= @profession.name %></h1>
<h3><%= @profession.description %></h3>
<h3>本职业目前共有<%= @skills_num %>个技能</h3>
<p>
  <%= link_to 'Back' , professions_path %>
</p>

app/views/skills/index.html.erb
<h1>Skills#index</h1>
<p>Find me in app/views/skills/index.html.erb</p>